version: '2'

services:  
  nginx:
    container_name: lb
    build: ./nginx
    links:
      - app-1:app-1
      - app-2:app-2
      - app-3:app-3
    ports:
      - 4000:80
    depends_on:
      - app-1
      - app-2
      - app-3

  app-1:
    container_name: instance-1
    image: bbd/node-web-app 
    environment:
      - MESSAGE="First instance"
    ports:
      - 8080

  app-2:
    container_name: instance-2
    image: bbd/node-web-app 
    environment:
      - MESSAGE="Second instance"    
    ports:
      - 8080

  app-3:
    container_name: instance-3
    image: bbd/node-web-app 
    environment:
      - MESSAGE="Third instance"    
    ports:
      - 8080